# permissions for end users to view awsec2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsec2-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-vmstate-operator
    app.kubernetes.io/part-of: ansible-vmstate-operator
    app.kubernetes.io/managed-by: kustomize
  name: awsec2-viewer-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsec2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsec2s/status
  verbs:
  - get
